# Generated by Django 3.1 on 2021-07-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20210703_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='feet',
            field=models.CharField(choices=[('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='types',
            field=models.CharField(choices=[('মোটা', 'মোটা'), ('চিকন', 'চিকন')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='feet',
            field=models.CharField(choices=[('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='types',
            field=models.CharField(choices=[('মোটা', 'মোটা'), ('চিকন', 'চিকন')], max_length=200, null=True),
        ),
    ]
