# Generated by Django 3.1 on 2021-07-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20210703_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='color',
            field=models.CharField(choices=[('NOF', 'NOF'), ('পাতলা', 'পাতলা'), ('লোম', 'লোম'), ('CNG', 'CNG'), ('টিয়া', 'টিয়া'), ('লাল', 'লাল'), ('ব্লো', 'ব্লো')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='company',
            field=models.CharField(choices=[('PHP', 'PHP'), ('JALALABAD', 'JALALABAD')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='mm',
            field=models.CharField(choices=[('120', '120'), ('150', '150'), ('170', '170'), ('190', '190'), ('200', '200'), ('260', '260'), ('320', '320'), ('340', '340'), ('420', '420'), ('25', '25'), ('30', '30'), ('48', '48')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='types',
            field=models.CharField(choices=[('মোটা', 'মোটা'), ('চিকন', 'চিকন'), ('বক্স', 'বক্স')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('NOF', 'NOF'), ('পাতলা', 'পাতলা'), ('লোম', 'লোম'), ('CNG', 'CNG'), ('টিয়া', 'টিয়া'), ('লাল', 'লাল'), ('ব্লো', 'ব্লো')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.CharField(choices=[('PHP', 'PHP'), ('JALALABAD', 'JALALABAD')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mm',
            field=models.CharField(choices=[('120', '120'), ('150', '150'), ('170', '170'), ('190', '190'), ('200', '200'), ('260', '260'), ('320', '320'), ('340', '340'), ('420', '420'), ('25', '25'), ('30', '30'), ('48', '48')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='types',
            field=models.CharField(choices=[('মোটা', 'মোটা'), ('চিকন', 'চিকন'), ('বক্স', 'বক্স')], max_length=200, null=True),
        ),
    ]
