# Generated by Django 3.1 on 2021-07-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20210703_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='name',
            field=models.CharField(choices=[('NOF', 'NOF'), ('পাতলা', 'পাতলা'), ('লোম', 'লোম'), ('CNG', 'CNG'), ('টিয়া', 'টিয়া'), ('লাল', 'লাল'), ('ব্লো', 'ব্লো')], max_length=200, null=True),
        ),
    ]
