# Generated by Django 3.2.5 on 2021-07-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_history_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='types',
            field=models.CharField(choices=[('মোটা', 'মোটা'), ('চিকন', 'চিকন'), ('কালার', 'কালার'), ('বক্স', 'বক্স')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='types',
            field=models.CharField(choices=[('মোটা', 'মোটা'), ('চিকন', 'চিকন'), ('কালার', 'কালার'), ('বক্স', 'বক্স')], max_length=200, null=True),
        ),
    ]
