# Generated by Django 3.1 on 2021-07-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20210707_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['mm', 'feet']},
        ),
    ]
