# Generated by Django 3.1 on 2021-07-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20210707_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='color',
            field=models.CharField(choices=[('NOF', 'NOF'), ('Super', 'Super'), ('লোম', 'লোম'), ('-', '-'), ('CNG', 'CNG'), ('টিয়া', 'টিয়া'), ('লাল', 'লাল'), ('ব্লো', 'ব্লো')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='name',
            field=models.CharField(choices=[('NOF', 'NOF'), ('Super', 'Super'), ('লোম', 'লোম'), ('-', '-'), ('CNG', 'CNG'), ('টিয়া', 'টিয়া'), ('লাল', 'লাল'), ('ব্লো', 'ব্লো')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('NOF', 'NOF'), ('Super', 'Super'), ('লোম', 'লোম'), ('-', '-'), ('CNG', 'CNG'), ('টিয়া', 'টিয়া'), ('লাল', 'লাল'), ('ব্লো', 'ব্লো')], max_length=200, null=True),
        ),
    ]
