# Generated by Django 3.1 on 2021-07-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_auto_20210708_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='color',
        ),
        migrations.RemoveField(
            model_name='history',
            name='company',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.AlterField(
            model_name='history',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='types',
            field=models.CharField(choices=[('মোটা', 'মোটা'), ('চিকন', 'চিকন'), ('NOF', 'NOF'), ('লোম', 'লোম'), ('কালার', 'কালার'), ('বক্স', 'বক্স')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='types',
            field=models.CharField(choices=[('মোটা', 'মোটা'), ('চিকন', 'চিকন'), ('NOF', 'NOF'), ('লোম', 'লোম'), ('কালার', 'কালার'), ('বক্স', 'বক্স')], max_length=200, null=True),
        ),
    ]
